apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdtclient-deployment
  labels:
    app: rdtclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rdtclient
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rdtclient
    spec:
      containers:
      - name: rdtclient
        image: rogerfar/rdtclient:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6500
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - mountPath: "/media"
          name: symlinks-volume
        - mountPath: "/data/db"
          name: rdt-data
        - mountPath: "/downloads"
          name: host-volume
      volumes:
      - name: symlinks-volume
        persistentVolumeClaim:
          claimName: pvc-media-nfs
      - name: rdt-data
        persistentVolumeClaim:
          claimName: rdt-pvc
      - name: host-volume
        hostPath:
          path: /mnt/zurg/
          # Optional: specify the type of the hostPath. Use "DirectoryOrCreate" if you want the directory to be created if it does not already exist.
          type: Directory
