apiVersion: v1
kind: Service
metadata:
  name: rdtclient-service
spec:
  type: ClusterIP
  selector:
    app: rdtclient
  ports:
    - port: 6500
      targetPort: 6500
      protocol: TCP
      name: web