apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdtclient-deployment
  labels:
    app: rdtclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rdtclient
  template:
    metadata:
      labels:
        app: rdtclient
    spec:
      containers:
      - name: rdtclient
        #image: erix12/rdt-client:latest
        image: erix12/rdt-client@sha256:ca55c40daedd3d24a3ba51495acb98e7b8c200a7a45132a519d758601bbe1ef6
        imagePullPolicy: Always
        ports:
        - containerPort: 6500
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - mountPath: "/data/downloads"
          name: symlinks-volume
        - mountPath: "/data/db"
          name: rdt-data
        - mountPath: "/mnt/zurg/"
          name: host-volume
      volumes:
      - name: symlinks-volume
        persistentVolumeClaim:
          claimName: symlinks-pvc
      - name: rdt-data
        persistentVolumeClaim:
          claimName: rdt-pvc
      - name: host-volume
        hostPath:
          path: /mnt/zurg/
          # Optional: specify the type of the hostPath. Use "DirectoryOrCreate" if you want the directory to be created if it does not already exist.
          type: Directory
