apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: remux-data
  namespace: remux
  labels:
    app: remux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
