---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-password
  namespace: home-automation
spec:
  encryptedData:
    dbPassword: AgB6Mds2sGzkT2TDVy8urTOsejc944Rm33cdOZCKlXNJSKgsWG7WX41wW8/prszAC3v8AWKN2Hp9zGgL4wEwEcJgz3Y+JaAwuiLJc1UjlOBD/UyJuItF1g7+hq7yex+kFDjywNv4wSE9KE5TDIT7z7Qs8oD53z0SaXY1rmca0zBIws0gIDUMHSD0QH5Xx64DHbS+mNH8PtwsdcLoARVhL3HdxwDgSjXUne0SzT6vFO2IaGKfLCknwTo69e+D3XGACr7Vn6ZIlfff23XxxBR2OD8dgSzKoVy7UjgHsUEoZ8ULQ/u5kERxOP5jL2RjMC3U5zwV0/pVd3jHDzmStEg/uPv3nwqZAtMr5lFEIg+UlL5uccg3SVrAYPCGw5mKWjqGqh1kDEnx0gWnbQ3IcR66yGhz68g13FgrhQBK/nbIHutatkjhWfHlOIW0Vck/XLwyE9SA4ebMzPIB67rO/NdaigdMf7ZQosBeANuAlNJ3tUMiE9mtv3zAILVNavaAhbJzUENliQsqe8R44g3LiCCSfhkjR5q6N3IGVjRZXLPo+1TppcI4CkOsTghOT/6CwNQ2Yw5a/THs40jeOks4zHQU8guzgawcwiXE23qCjbkQGBZgXYOvZ1T8LRJf8ml2GDKJAep4gSHwKH9JzbI6AmHfLHxZdQ4bpoTOMnOzwa4sdWyIQjHRcVk87woormQ4rPZhy3vNjPdS
    rootPassword: AgCS8KaHiUIEVIvzXCykeMys19Wn9ofANF83WgGbmNQ8YySDCvFH03gz2qEkT159SjiRCOEoqzkV9tGMvagaaQRmQr9UV+hIiGzdcDJslvzW1ohKZ+LKavVXVhgVdUHogCE5Y+BsFxgDAC7VwAXTYW1qD9LutJXoA0yMWQXs9osU8QJyq6fAgi484oQfqje70FM6uR9OgExI14V2NCH/9GxdU8zViBi2w+q/jkD6DXy30A7RndRcP6UlEEDmY1yb2rrpM8+pIn7mq2a4S6S9vkGhd1oWwg+lebOH3ZreTKOo8USZoW59Xvk78DIsnImTlp41llzKB5AKkfbOjiU2wEnQdJtHBL2RdLxfNbFWQ+Ybjqm8OrhXhS3If3mmxZm1z307dyx8IYofY6QhHmH64IcFQ6VySPJ+/+xjUMaOj3rz0VD6KIdWHQrenYl6dAAGBUlH55w8gsY1R64GhwBN9s83ZKhW0CYdffqVbloNmEuC/1ySDKC7C2oc0wzk01GqW19SeSGPRSaxFNPa4JGF2xBxPs8f34GRYTeO1ZEB94RQXj0DWuIn4462kRsifFWI7aCAjz6ywh6fEKjM+JzGrAv+ODhguNjQXRKpsX3ckk1y4Pl4Duz03MhKgVfDYjTwjKz2Q73iwiF0PK0DVVlXcaJjLPUG/MPBOgdMbyURKe/1ysLE6OSTvooZVilTAnVgiPm5KlXf
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-password
      namespace: home-automation
