apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: home-automation
spec:
  serviceName: "mariadb-service"
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role
                operator: In
                values:
                - database
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "database"
        effect: "NoSchedule"
      containers:
      - name: mariadb
        image: linuxserver/mariadb:10.11.6
        imagePullPolicy: IfNotPresent
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-password
              key: rootPassword
        - name: TZ
          value: "Europe/London"
        - name: MYSQL_DATABASE
          value: "mariatest" #optional
        - name: MYSQL_USER
          value: "mariadb" #optional
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-password
              key: dbPassword
        ports:
        - name: mariadb-port
          containerPort: 3306
        volumeMounts:
          - name : mariadb-storage
            mountPath: /config
      restartPolicy: Always
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-sts-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: home-automation
  labels:
    app: mariadb
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.11.203
spec:
  ports:
  - name: mariadb-port
    port: 3306
  selector:
    app: mariadb
  type: LoadBalancer
