apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-sts
spec:
  serviceName: "mariadb-service"
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: linuxserver/mariadb:10.11.6
        imagePullPolicy: IfNotPresent
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-password
              key: rootPassword
        - name: TZ
          value: "Europe/London"
        - name: MYSQL_DATABASE
          value: "mariatest" #optional
        - name: MYSQL_USER
          value: "mariadb" #optional
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-password
              key: dbPassword
        ports:
        - name: mariadb-port
          containerPort: 3306
        volumeMounts:
          - name : mariadb-storage
            mountPath: /config
      restartPolicy: Always
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-sts-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: mariadb
spec:
  ports:
  - name: mariadb-port
    port: 3306
  selector:
    app: mariadb
  type: LoadBalancer
  loadBalancerIP: 192.168.11.203
