apiVersion: v1
kind: Service
metadata:
  name: truenas-minio-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001

---
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas-minio-service
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.179
    ports:
      - port: 9001

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: minio.erix-homelab.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: truenas-minio-service
            port:
              number: 9001
  tls:
  - secretName: erix-homelab-site-tls
    hosts:
    - minio.erix-homelab.site
