apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceberg-deployment
  labels:
    app: iceberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iceberg
  template:
    metadata:
      labels:
        app: iceberg
    spec:
      containers:
      - name: iceberg
        image: spoked/iceberg:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: ORIGIN
          value: "http://192.168.11.209:3000"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: data-volume
          mountPath: /iceberg/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: iceberg-pvc