apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  labels:
    app: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:s6
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/srv/download"
          name: symlinks-volume
        - mountPath: "/database"
          name: filebrowser-data
        - mountPath: "/srv/zurg/"
          name: zurg-volume
        - mountPath: /config/settings.json
          subPath: filebrowser.json
          name: filebrowser-config
      volumes:
      - name: symlinks-volume
        persistentVolumeClaim:
          claimName: symlinks-pvc
      - name: filebrowser-data
        persistentVolumeClaim:
          claimName: filebrowser-pvc
      - name: zurg-volume
        hostPath:
          path: /mnt/zurg/
          # Optional: specify the type of the hostPath. Use "DirectoryOrCreate" if you want the directory to be created if it does not already exist.
          type: Directory
      - name: filebrowser-config
        configMap:
          name: filebrowser-config