apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
  namespace: default
data:
  filebrowser.json: |
    {
      "port": 8080,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/database/filebrowser.db",
      "root": "/srv"
    }