apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-media-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/erix/homelab.git'
    targetRevision: HEAD
    path: plex
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
