apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-confidence-website
  namespace: flux-system
spec:
  interval: 10m
  path: ../../apps/hello-confidence-website
  prune: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-system
  images:
    - name: ghcr.io/fuloptimea-rgb/hello-confidence-website
      newTag: main-62-sha-95a783b6451b8e35d06a89305bf4f2ba9f12e29a # {"$imagepolicy":"flux-system:hello-confidence-website:tag"}
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: hello-confidence-website
  namespace: flux-system
spec:
  image: ghcr.io/fuloptimea-rgb/hello-confidence-website
  interval: 1m
  secretRef:
    name: ghcr-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: hello-confidence-website
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hello-confidence-website
  filterTags:
    pattern: "^main-(?P<run>[0-9]+)-sha-[a-f0-9]{40}$"
    extract: "$run"
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: hello-confidence-website
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "chore: update hello-confidence-website image"
    push:
      branch: main
  update:
    path: ./clusters/new/apps
    strategy: Setters
