apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Networking
  - traefik.yaml
  - mail-relay.yaml
  # Home Automation
  - mariadb.yaml
  - home-assistant.yaml
  - mqtt.yaml
  - zigbee2mqtt.yaml
  # Media
  - calibre.yaml
  - aiometadata.yaml
  - aiostreams.yaml
  # Network
  - unifi.yaml
  # Tools
  - n8n.yaml
  - ib-gateway.yaml
