apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: splitbot
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/erix/splitbot
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: splitbot
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/overlays/local
  prune: true
  wait: true
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: splitbot
  images:
    - name: ghcr.io/erix/splitbot
      newTag: main-9-sha-ea4ca3b24f5432324abe20d2c0d4b61eeb71777a # {"$imagepolicy":"flux-system:splitbot:tag"}
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: splitbot
      namespace: splitbot
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: splitbot
  namespace: flux-system
spec:
  image: ghcr.io/erix/splitbot
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: splitbot
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: splitbot
  filterTags:
    pattern: "^main-(?P<run>[0-9]+)-sha-[a-f0-9]{40}$"
    extract: "$run"
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: splitbot
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        chore: update splitbot image

        Updated files:
        {{- range $filename, $_ := .Updated.Files }}
        - {{ $filename }}
        {{- end }}
    push:
      branch: main
  update:
    path: ./clusters/new/apps
    strategy: Setters
