apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: home-automation
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.11.230
spec:
  type: LoadBalancer
  selector:
    app: mosquitto
  ports:
  - port: 8883
