apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  # namespace: homeassistant
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.11.230
  selector:
    app: mosquitto
  ports:
  - port: 8883
