apiVersion: v1
kind: Pod
metadata:
  name: test-alert-trigger
  namespace: default
spec:
  containers:
  - name: stress
    image: polinux/stress
    resources:
      requests:
        memory: "10Gi"
        cpu: "10"
      limits:
        memory: "10Gi"
        cpu: "10"
    command: ["sleep", "3600"]
