---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgC3Qv8Y8pVbHk+IntNjE73jHIFetVpd7wEc25yXw1KB7+QNwnml9YhJC8ZjFIAdST2+R1oLs3IdLX6fMJcq5Ltn4wiBN7PNIVDjncnIxJpmqTeCYabjq76FELpnzWLr3YCsMmTEX0cFOknLJf9hMWZRKk7ZmTIDGYAd/x/KAfsZF1uJQy2CJvP+I6HXqF7irG3pUc3P6/Vz6O6MhC1y6DAmmRh7wQsTuC/i/IV+1yIykUyk9EvgP+fi+mEbifPogWl8fd0n5PdfcU8t3IqrCBATnazbMhoEF6t6ygAaAuOqow/IkD2MwoLVjeBJb4xH7j4anbwgVuo/HbrnoZbDy/xryQWVYrfpZK6TGheHLIg2nuFW2ihuw7KOh+e6GmH0IHw9oQPNFyN+3SDnS/cfKyV5ffmdHCPT5Dk52PNbPmah46D6kIJkC/KOmvvvqMffqJy1RXTO1JwF5rrawnjDvcejAn8s2FBH+91++rUlIOX6KZmygF7JC9FGWOE2MGH3GEsvUSUW/+oWZAiO+WE1N7iTqCa0gHZzpbFtrIPPGjC4riOPU11pg1FbfKEtbakopfVl/s4WU9JnWYrzt9b69xm1BG7Dlg7KZFaoJLhNxzi5qkkGSf2U1L1MXBlcKNSB9N037DxJic4V9NFFjpb7MELuHypEzTOhgmrDCYDMLowt4KjPWG7SxZe9Qw/2TZTxbiK/9MC/HUMpcrsOh3S8JqJWEA==
    client_secret: AgACBhTDPstUmTYFa/0luroCB8Q2rnBBrzqCtAVJX0g60W0sUxwuqnTajody4o45lBvlyXJELscZrFWH1LbUGgJawo38vhO3udqP3rSz/HdpyBe15aQOBqVGQ9Q8XS0CBCDXwBAwF7H5HEDtfplQB8zdQ6nphDhAIRc8Yh5WoJvcATdJi8zTVPUbkbuRiBKeq58T+kZ8cm8JFMn6n1xcEZxnDmnW7E08F1s4k6HzyILgNRdncyJI4Qq4LXRijuJEiVTLTate4M2q+GuKCs2O4xCp7TkpECeLtoSO5N1E1GkhlU4FAckfyM3fsaxCye89cbAUMeT/SmJZgmCOxLA3GUXmFBKzMrV7TwZckQfvJgshc/IdF8AIzy5+G5CfXkWk5355A1/6+gxCodHMP98awuWnp8w6Pm6SSwaApodETyFa0HNiXN/cSCo2OG8linZbc2p4skU9LPZQrQdXLxz7knqbSCfpitAUF9qms0cutfCj4QUU1gKVEgXCuX7i6qRUviNivxdsKzMsazZon/7fJWpMgMGx4rx96LfarTnk+1YzQHDLBkqguvS27YkYlX2AePK5bmblYB3bs0Sg2jwiWqfafcc/FuL+DRDWbGN1kibnerGo4vAWUhpFYqyycIA/M64eQvZ47QWFll+jXlfaaN6gJXoHto6NNxjR/pkONJlDe2NcweD0UX8S01v/v3c/vV2SVj/ORH+3Wa7ZmbxUawBKoSzhTRZHXFjUX1AHTPT2UZ4YhRR8vWU5/zutHQAVID+hFznI3sV7Z7oIGNBd55Cj
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
