apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-confidence-custom-domains
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: hello-confidence.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-confidence-website
                port:
                  number: 80
    - host: www.hello-confidence.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-confidence-website
                port:
                  number: 80
