apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - signup-deployment.yaml
  - signup-service.yaml
  - signup-networkpolicy.yaml
configMapGenerator:
  - name: hello-confidence-signup
    files:
      - signup-server.py
