apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-downloads-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.179
  share: /mnt/tank/downloads/data
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: pv-downloads-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-downloads-csi
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 192.168.1.179#data#data
    volumeAttributes:
      server: 192.168.1.179
      share: /mnt/tank/downloads/data

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-downloads-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-downloads-nfs
  storageClassName: nfs-downloads-csi