apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aiometadata-redis-data
  namespace: stremio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
