apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
  namespace: home-automation
spec:
  selector:
    app: homeassistant-label
  ports:
  - name: homeassistant
    port: 8123
    targetPort: 8123
  # - name: filebrowser
  #   port: 8080
  #   targetPort: 80
  - name: netbios-ssn
    port: 139
    targetPort: 139
  - name: microsoft-ds
    port: 445
    targetPort: 445
  type: LoadBalancer
