apiVersion: v1
kind: Service
metadata:
  name: ibeam
  namespace: default
  labels:
    app: ibeam
  annotations:
    metallb.io/ip-allocated-from-pool: homelab-pool
    tailscale.com/expose: "true"
spec:
  type: LoadBalancer
  selector:
    app: ibeam
  ports:
    - name: rest-api
      port: 5000
      targetPort: 5000
      protocol: TCP
