apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibeam-autologin
  namespace: default
  labels:
    app: ibeam-autologin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibeam-autologin
  namespace: default
  labels:
    app: ibeam-autologin
rules:
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    resourceNames: ["ibeam-autologin"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibeam-autologin
  namespace: default
  labels:
    app: ibeam-autologin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibeam-autologin
subjects:
  - kind: ServiceAccount
    name: ibeam-autologin
    namespace: default