apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ibeam-deployment.yaml
  - ibeam-service.yaml
  - ibeam-inputs.yaml
  - ibeam-autologin.yaml
configMapGenerator:
  - name: ibeam-autologin
    files:
      - ibeam-autologin.py
    options:
      disableNameSuffixHash: true
      labels:
        app: ibeam-autologin
