apiVersion: v1
kind: Service
metadata:
  name: mail-relay
  labels:
    app: mail-relay
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.11.225
spec:
  type: LoadBalancer
  selector:
    app: mail-relay
  ports:
    - name: smtp
      protocol: TCP
      port: 25
      targetPort: 25
    - name: submission
      protocol: TCP
      port: 587
      targetPort: 587
