apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aiostreams
  namespace: stremio
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - aiostreams.erix-homelab.site
    secretName: erix-homelab-site-tls
  rules:
  - host: aiostreams.erix-homelab.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aiostreams
            port:
              number: 3000
