apiVersion: v1
kind: Service
metadata:
  name: aiostreams
  namespace: stremio
  labels:
    app: aiostreams
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: aiostreams
