apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ib-gateway-config-pvc
  namespace: default
  labels:
    app: ib-gateway
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
