apiVersion: apps/v1
kind: Deployment
metadata:
  name: z2m
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: z2m
  template:
    metadata:
      labels:
        app: z2m
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab-03
      containers:
      - name: z2m
        image: koenkk/zigbee2mqtt:2.0.0 
        imagePullPolicy: IfNotPresent
        env:
          - name: TZ
            value: Europe/London
          - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
            value: "mqtt://mosquitto-service.home-automation.svc.cluster.local:8883"
          - name: ZIGBEE2MQTT_CONFIG_MQTT_USER
            value: "z2m"
          - name: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
            value: "password"
        securityContext:
          privileged: true
        ports:
          - containerPort: 8099
        volumeMounts:
          - name: z2m-data
            mountPath: /app/data
          - name: z2m-udev
            mountPath: /run/udev
          - name: ttyacm
            mountPath: /dev/ttyUSB0
      volumes:
        - name: z2m-data
          persistentVolumeClaim:
            claimName: z2m-pvc
        - name: z2m-udev
          hostPath:
            path: /run/udev
        - name: ttyacm
          hostPath:
            path: /dev/ttyUSB0
