apiVersion: v1
kind: Service
metadata:
  name: iceberg-service
spec:
  type: LoadBalancer # or LoadBalancer, depending on your environment and needs
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: iceberg
