apiVersion: v1
kind: Service
metadata:
  name: proxmox-service
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/service.serversScheme: https
spec:
  ports:
  - protocol: TCP
    port: 8006
    targetPort: 8006

---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-service
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.11.20
    ports:
      - port: 8006

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxmox-ingress
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: proxmox.erix-homelab.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proxmox-service
            port:
              number: 8006
  tls:
  - secretName: erix-homelab-site-tls
    hosts:
    - proxmox.erix-homelab.site
